# Generated by Django 3.2.7 on 2021-11-03 14:53

import cloudinary.models
from django.db import migrations
import django.utils.timezone
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211103_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
